Allow to hide any of the header buttons and update the Readme with the new options
WorkAroundOnline/react-image-annotate pull request #178
Opened 2021-10-04 11:51 UTC by josepdecid

I've seen some issues like #104 that requested a way to choose which buttons to show or hide from the header bar. I have found the same "problem" (lack of feature) with a project of mine. Checking the code, I've seen that there were already a `hidePrev` and `hideNext` buttons that were not well documented.

Therefore, I have added a hide option for the rest of the buttons: Clone, Settings, Save and FullScreen/Window. I have also added the information about the existence of these properties in the [Readme Props section](https://github.com/UniversalDataTool/react-image-annotate#props).

I've noticed now that there are a noticeable amount of changes with the imports. Still, it's just the IDE that auto-sorted it automatically without me noticing it.

2021-10-14 22:46 UTC, seveibar requested changes
Good to merge but recommending you run prettier

2021-10-15 15:01 UTC, seveibar approved these changes

2021-10-15 15:01 UTC, merged

2021-11-15 10:48 UTC, josepdecid commented
Hello @seveibar! It seems that the deployment pipeline has failed, can you check the node version that is failing?
Thanks a lot!

2021-12-28 00:23 UTC, Cr7st commented
It seems that these props don't work in my app. I've set these hide props to be true but these buttons are still displayed.

2023-12-18 11:01 UTC, SuhaibMaraqa commented
@Cr7st me too, have you found any solution ?